//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonelOtomasyonu.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personeller
    {
        public int PersonelID { get; set; }
        public string PersonelAdi { get; set; }
        public string PersonelSoyadi { get; set; }
        public System.DateTime DogumTarihi { get; set; }
        public string Telefon { get; set; }
        public string MailAdresi { get; set; }
        public string EvAdresi { get; set; }
        public System.DateTime İseGirisTarihi { get; set; }
        public string Unvan { get; set; }
        public byte[] Fotografi { get; set; }
        public string TcNO { get; set; }
    }
}
