//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonelOtomasyonu.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PersonelBilgisiEntities : DbContext
    {
        public PersonelBilgisiEntities()
            : base("name=PersonelBilgisiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<KullanıcıAdı> KullanıcıAdı { get; set; }
        public virtual DbSet<Personeller> Personellers { get; set; }
    }
}
